FROM node:20

RUN wget https://releases.hashicorp.com/terraform/1.7.3/terraform_1.7.3_linux_amd64.zip;  \
    unzip terraform_1.7.3_linux_amd64.zip;  \
    mv terraform /usr/local/bin/;  \
    chmod a+x /usr/local/bin/terraform;  \
    rm -f terraform_1.7.3_linux_amd64.zip;  \
    terraform --version;  \
    npm install -g cdktf-cli@0.19.0; 
