visibility: private
allow_merge_commit: true
allow_squash_merge: true
allow_rebase_merge: true
allow_auto_merge: true
delete_branch_on_merge: false
auto_init: true
default_branch: main
archive_on_destroy: true
allow_update_branch: false
has_issues: true
