metadata:
  name: branch_policy_none
  description: The custom policy for importing a new repository

type: none
protections:
  pattern: main
  enforceAdmins: false
  requireSignedCommits: true
  allowsForcePushes: false
  allowDeletions: false
  requiredLinearHistory: true
  requiredPullRequestReviews:
    - dismissStaleReviews: true
      requireCodeOwnerReviews: true
      requiredApprovingReviewCount: 1
