name: Pr verify

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  pr-verify:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v4
      
      - name: Unit tests
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make init
          make test

      